language: node_js
node_js: 
  - "8.7.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - build-essential
      - g++-4.8
before_install:
  - export CXX="g++-4.8"
branches:
  only:
  - master
script:
- echo "Deploy!!"
install:
- npm install
- npm run start-rpcs
- sleep 5
- npm run test
after_success:
env:
  global:
