language: node_js
node_js: 
  - "8.7.0"
branches:
  only:
  - master
install:
- npm install
script:
- ganache-cli -p 8545 -a 10 -d -n -i 15 -m "exchange neither monster ethics bless cancel ghost excite business record warfare invite" > /dev/null &
- kaya --accounts scripts/rpcs/account-fixtures.json > scripts/TestRPCData/$moduleName.output.log & > /dev/null &
- sleep 5
- npm run coveralls
after_success:

env:
  global:
